// <auto-generated />
using System;
using FarmManager.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FarmManager.Infrastructure.Migrations
{
    [DbContext(typeof(FarmManagerDbContext))]
    [Migration("20250606154740_AddFieldName")]
    partial class AddFieldName
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("FarmManager.Domain.Entities.CropRotationPlan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("FieldId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("FieldId")
                        .IsUnique();

                    b.ToTable("CropRotationPlans");
                });

            modelBuilder.Entity("FarmManager.Domain.Entities.CropType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CropRotationPlanId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("HarvestingPeriodId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CropRotationPlanId");

                    b.HasIndex("HarvestingPeriodId");

                    b.ToTable("CropTypes");
                });

            modelBuilder.Entity("FarmManager.Domain.Entities.Field", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("AreaInHectares")
                        .HasColumnType("REAL");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Fields");
                });

            modelBuilder.Entity("FarmManager.Domain.Entities.MonthPeriod", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CropTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PeriodEndingMonth")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PeriodStartingMonth")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CropTypeId");

                    b.ToTable("MonthPeriods");
                });

            modelBuilder.Entity("FarmManager.Domain.Entities.CropRotationPlan", b =>
                {
                    b.HasOne("FarmManager.Domain.Entities.Field", "Field")
                        .WithOne("CropRotationPlan")
                        .HasForeignKey("FarmManager.Domain.Entities.CropRotationPlan", "FieldId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Field");
                });

            modelBuilder.Entity("FarmManager.Domain.Entities.CropType", b =>
                {
                    b.HasOne("FarmManager.Domain.Entities.CropRotationPlan", null)
                        .WithMany("PlannedCrops")
                        .HasForeignKey("CropRotationPlanId");

                    b.HasOne("FarmManager.Domain.Entities.MonthPeriod", "HarvestingPeriod")
                        .WithMany()
                        .HasForeignKey("HarvestingPeriodId");

                    b.Navigation("HarvestingPeriod");
                });

            modelBuilder.Entity("FarmManager.Domain.Entities.MonthPeriod", b =>
                {
                    b.HasOne("FarmManager.Domain.Entities.CropType", null)
                        .WithMany("SeedingPeriods")
                        .HasForeignKey("CropTypeId");
                });

            modelBuilder.Entity("FarmManager.Domain.Entities.CropRotationPlan", b =>
                {
                    b.Navigation("PlannedCrops");
                });

            modelBuilder.Entity("FarmManager.Domain.Entities.CropType", b =>
                {
                    b.Navigation("SeedingPeriods");
                });

            modelBuilder.Entity("FarmManager.Domain.Entities.Field", b =>
                {
                    b.Navigation("CropRotationPlan");
                });
#pragma warning restore 612, 618
        }
    }
}
